name: Single Instance Blue-Green Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  BLUE_TG_ARN: ${{ secrets.BLUE_TARGET_GROUP_ARN }}
  GREEN_TG_ARN: ${{ secrets.GREEN_TARGET_GROUP_ARN }}
  ALB_LISTENER_ARN: ${{ secrets.ALB_LISTENER_ARN }}
  LAUNCH_TEMPLATE_ID: ${{ secrets.LAUNCH_TEMPLATE_ID }}
  PRIVATE_SUBNET_ID: ${{ secrets.PRIVATE_SUBNET_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        id: set_tag
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT
          echo "TAG=$TAG" >> $GITHUB_ENV


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          for service in db api app; do
            IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/quotes-${service}"
            docker build --no-cache -t $IMAGE_NAME:${TAG} -t $IMAGE_NAME:latest $GITHUB_WORKSPACE/$service
            docker push $IMAGE_NAME:${TAG}
            docker push $IMAGE_NAME:latest
          done

      - name: Upload deployment files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          sed -i "s|build: ./db|image: ${{ secrets.DOCKER_USERNAME }}/quotes-db:${TAG}|g" docker-compose.yml
          sed -i "s|build: ./api|image: ${{ secrets.DOCKER_USERNAME }}/quotes-api:${TAG}|g" docker-compose.yml
          sed -i "s|build: ./app|image: ${{ secrets.DOCKER_USERNAME }}/quotes-app:${TAG}|g" docker-compose.yml

          aws s3 cp docker-compose.yml s3://${{ secrets.DEPLOYMENT_BUCKET }}/deployments/${TAG}/
          aws s3 cp deployment/ s3://${{ secrets.DEPLOYMENT_BUCKET }}/deployments/${TAG}/deployment/ --recursive

          echo " Deployment files uploaded to S3"

  provision-green:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      green_instance_id: ${{ steps.launch.outputs.instance_id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Launch single green instance
        id: launch
        run: |
          echo "Launching new green instance..."
          INSTANCE_ID=$(aws ec2 run-instances  --launch-template LaunchTemplateId=${{ env.LAUNCH_TEMPLATE_ID }} --count 1 \
            --subnet-id ${{ env.PRIVATE_SUBNET_ID }} \
            --tag-specifications "ResourceType=instance,Tags=[
              {Key=Name,Value=quotes-app-green}
            ]"  --query 'Instances[0].InstanceId' \
            --output text)
          
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT
          echo "Launched green instance"

      - name: Wait for green instance to be ready
        run: |
          echo "Waiting for instance to be running..."
          aws ec2 wait instance-running --instance-ids ${{ steps.launch.outputs.instance_id }}

          echo "Instance is running. Waiting for initialization to complete..."
          sleep 200



  deploy:
    needs: [build, provision-green]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy via SSM
        run: |
          echo "=== Deploying to green instance ==="
          echo "Instance ID: ${{ needs.provision-green.outputs.green_instance_id }}"
          echo "Image Tag: ${{ needs.build.outputs.image_tag }}"

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ needs.provision-green.outputs.green_instance_id }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy quotes app ${{ needs.build.outputs.image_tag }}" \
            --timeout-seconds 1800 \
            --parameters 'commands=[
              "#!/bin/bash",
              "set -ex",
              "sudo mkdir -p /home/ubuntu/quotes-app/deployment",
              "sudo chown -R ubuntu:ubuntu /home/ubuntu/quotes-app",
              "cd /home/ubuntu/quotes-app",
              "echo \"Downloading files from S3...\"",
              "aws s3 cp s3://${{ secrets.DEPLOYMENT_BUCKET }}/deployments/${{ needs.build.outputs.image_tag }}/docker-compose.yml .",
              "aws s3 cp s3://${{ secrets.DEPLOYMENT_BUCKET }}/deployments/${{ needs.build.outputs.image_tag }}/deployment/ ./deployment/ --recursive",
              "chmod +x deployment/*.sh",
              "echo \"Starting deployment script...\"",
              "bash deployment/deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ needs.build.outputs.image_tag }} ${{ secrets.DOCKER_PASSWORD }} green"
            ]' \
            --query 'Command.CommandId' \
            --output text)
          echo "Sent SSM command with Command ID: $COMMAND_ID"
          sleep 200


  register-green:
    needs: [provision-green, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Register to green target group and wait for healthy
        run: |
          aws elbv2 register-targets --target-group-arn ${{ env.GREEN_TG_ARN }} --targets Id=${{ needs.provision-green.outputs.green_instance_id }}

          sleep 150


  configure-canary:
    needs: register-green
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set traffic split to 80% Blue, 20% Green
        run: |
          aws elbv2 modify-listener  --listener-arn ${{ env.ALB_LISTENER_ARN }} \
            --default-actions Type=forward,ForwardConfig="{
              TargetGroups=[
                {TargetGroupArn=${{ env.BLUE_TG_ARN }},Weight=80},
                {TargetGroupArn=${{ env.GREEN_TG_ARN }},Weight=20}
              ],
              TargetGroupStickinessConfig={Enabled=false}
            }"

  approve:
    needs: configure-canary
    runs-on: ubuntu-latest
    environment: production-approval
    steps:
      - name: QA Approval Gate
        run: |
          echo "Deployment paused for QA testing"
          echo "Blue: 80% traffic, Green: 20% traffic"

  complete-deployment:
    needs: [provision-green, approve]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: blue-instance
        run: |
          BLUE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Environment,Values=blue" "Name=instance-state-name,Values=running" \
            --query 'Reservations[0].Instances[0].InstanceId' --output text 2>/dev/null || echo "")
          echo "blue_id=$BLUE_ID" >> $GITHUB_OUTPUT

      - name: Shift 100% traffic to green target group
        run: |
          aws elbv2 modify-listener --listener-arn ${{ env.ALB_LISTENER_ARN }} --default-actions Type=forward,TargetGroupArn=${{ env.GREEN_TG_ARN }}

      - name: Deregister and terminate old blue instance
        if: steps.blue-instance.outputs.blue_id != '' && steps.blue-instance.outputs.blue_id != 'None'
        run: |
          aws elbv2 deregister-targets --target-group-arn ${{ env.BLUE_TG_ARN }} --targets Id=${{ steps.blue-instance.outputs.blue_id }}
          sleep 30
          aws ec2 terminate-instances --instance-ids ${{ steps.blue-instance.outputs.blue_id }}

      - name: Promote green instance to blue target group
        run: |
          aws ec2 create-tags --resources ${{ needs.provision-green.outputs.green_instance_id }} --tags Key=Environment,Value=blue Key=Name,Value=quotes-app-blue
          aws elbv2 register-targets --target-group-arn ${{ env.BLUE_TG_ARN }} --targets Id=${{ needs.provision-green.outputs.green_instance_id }}
          sleep 15
          aws elbv2 modify-listener --listener-arn ${{ env.ALB_LISTENER_ARN }} --default-actions Type=forward,TargetGroupArn=${{ env.BLUE_TG_ARN }}
          sleep 10
          aws elbv2 deregister-targets --target-group-arn ${{ env.GREEN_TG_ARN }} --targets Id=${{ needs.provision-green.outputs.green_instance_id }}
